markdown: kramdown
name: Code for DC
url: https://codefordc.org
title: Code for DC
description: "We bring together community members and subject-matter experts with data enthusiasts and techies to help make a better DC for all of its residents."
encoding: utf-8
timezone: America/New_York
gems:
  - jekyll-redirect-from
future: true
